print('Input 1st number:')
a = int(input())
print('Input 2nd number: ')
b = int(input())
print('a + b = ')
print(a+b)
print('a - b = ')
print(a-b)
print('a * b = ')
print(a*b)
print('a / b = ')
print(a/b)
print('a % b = ')
print(a%b)
print('a ** b = ')
print(a**b)
